// <auto-generated />
using Db.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240129134414_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Db.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Storage")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "produto um",
                            Name = "ProdutoUm",
                            Price = 1f,
                            Storage = 1,
                            Weight = 1f
                        },
                        new
                        {
                            Id = 2,
                            Description = "produto dois",
                            Name = "ProdutoDois",
                            Price = 2f,
                            Storage = 2,
                            Weight = 2f
                        },
                        new
                        {
                            Id = 3,
                            Description = "produto tres",
                            Name = "ProdutoTres",
                            Price = 3f,
                            Storage = 3,
                            Weight = 3f
                        },
                        new
                        {
                            Id = 4,
                            Description = "produto exemplo",
                            Name = "Exepmlo1",
                            Price = 10f,
                            Storage = 5,
                            Weight = 4f
                        },
                        new
                        {
                            Id = 5,
                            Description = "produto exemplo",
                            Name = "Exemplo2",
                            Price = 20f,
                            Storage = 5,
                            Weight = 5f
                        },
                        new
                        {
                            Id = 6,
                            Description = "produto exemplo",
                            Name = "Exemplo3",
                            Price = 30f,
                            Storage = 5,
                            Weight = 6f
                        });
                });

            modelBuilder.Entity("Db.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Access")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Access = 0,
                            Cpf = "10010010010",
                            Email = "user@user.com.br",
                            Name = "User",
                            Password = "user"
                        },
                        new
                        {
                            Id = 2,
                            Access = 1,
                            Cpf = "20020020020",
                            Email = "mod@mod.com.br",
                            Name = "Mod",
                            Password = "mod"
                        },
                        new
                        {
                            Id = 3,
                            Access = 2,
                            Cpf = "30030030030",
                            Email = "admin@admin.com.br",
                            Name = "Admin",
                            Password = "admin"
                        },
                        new
                        {
                            Id = 4,
                            Access = 0,
                            Cpf = "00100100101",
                            Email = "teste@teste.com.br",
                            Name = "Teste",
                            Password = "teste"
                        },
                        new
                        {
                            Id = 5,
                            Access = 1,
                            Cpf = "00200200202",
                            Email = "exmpl@exmpl.com.br",
                            Name = "Exemplo",
                            Password = "exmpl"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
